library(ggplot2)
library(reshape2)
head(tips)
data(tips, package = 'reshape2')
GGally::ggpairs(tips)
unique(tips$day)
unique(tips$sex)
summary(tips)
t.test(tips$tip, alternative = 'two.sided', mu=2.5)
t.test(tips$tip, alternative = 'greater', mu=2.5)
sd(tips$tip)
aggregate(tip ~ sex, data = tips, var)
shapiro.test(tips$tip)
shapiro.test(tips$tip[tips$sex=="Female"])
shapiro.test(tips$tip[tips$sex=="Male"])
ggplot(tips, aes(x=tip, fill=sex)) +
  geom_histogram(binwidth = .5, alpha=1/2)
