require(ggplot2)
data("diamonds")
head(diamonds)

aggregate(price ~ cut, diamonds, mean)
aggregate(price ~ cut + color, diamonds, mean)
aggregate(cbind(price, carat) ~ cut, diamonds, mean)
mean(diamonds$price)
mean(diamonds$carat)
hist(diamonds$carat)
aggregate(cbind(price, carat) ~ cut + color, diamonds, mean)
